Add Overview Custom Node with Trainer checkbox
icivann/ivann pull request #111
Opened 2020-11-25 15:32 UTC by lancelotblanchard

Now, Editors can set their own `customNodeType` parameter (defaults to `Common`) to another Custom Node class. That's now the case with the Overview editor which has an `OverviewCustom` node, with a `Trainer` checkbox.

2020-11-25 16:48 UTC, gidonkatten requested changes
One bug I noticed is what happens if you edit a function and delete `return` or add a `return`. Then the change is not reflected in the nodes. I have a fix but it would probably be best if we discussed as I am unsure exactly what we need

2020-11-26 16:38 UTC, lancelotblanchard commented
Good catch! I fixed this using a new  `returnStatement: { removed: boolean; added: boolean };` parameter in the `FuncDiff` interface. Tell me if that looks good to you.

2020-11-26 16:49 UTC, gidonkatten commented
> Good catch! I fixed this using a new `returnStatement: { removed: boolean; added: boolean };` parameter in the `FuncDiff` interface. Let me know if that looks good to you.

I think this is good. Did you check that it saves? I think it should automatically as it should detect the body of the function has changed

2020-11-26 16:51 UTC, gidonkatten commented
Merge conflicts need to be fixed btw

2020-11-26 16:53 UTC, gidonkatten submitted a review, later dismissed

2020-11-26 20:53 UTC, KacperKazan approved these changes
great job Lancelot!! Keep it up!!!

2020-11-26 20:53 UTC, merged

2020-11-26 20:54 UTC, lancelotblanchard commented
> great job Lancelot!! Keep it up!!!

Thank you.